// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe3QsaNnt3P3xac-u15wWtcZmzjoG8dDg',
    appId: '1:250235140199:web:54dd99ebaa749e8b377cc2',
    messagingSenderId: '250235140199',
    projectId: 'styleleague-895e8',
    authDomain: 'styleleague-895e8.firebaseapp.com',
    storageBucket: 'styleleague-895e8.firebasestorage.app',
    measurementId: 'G-SGSFLHCREL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsKSVOkAFipM9nv-E1-zKO2VQenlKIpFE',
    appId: '1:250235140199:android:ca240c9a06a9c295377cc2',
    messagingSenderId: '250235140199',
    projectId: 'styleleague-895e8',
    storageBucket: 'styleleague-895e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAriIeAoq52G5Ekmar0bBSauRU9nvlo3cs',
    appId: '1:250235140199:ios:ca533ab180a61337377cc2',
    messagingSenderId: '250235140199',
    projectId: 'styleleague-895e8',
    storageBucket: 'styleleague-895e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAriIeAoq52G5Ekmar0bBSauRU9nvlo3cs',
    appId: '1:250235140199:ios:ca533ab180a61337377cc2',
    messagingSenderId: '250235140199',
    projectId: 'styleleague-895e8',
    storageBucket: 'styleleague-895e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe3QsaNnt3P3xac-u15wWtcZmzjoG8dDg',
    appId: '1:250235140199:web:7fcfeee703ea4d75377cc2',
    messagingSenderId: '250235140199',
    projectId: 'styleleague-895e8',
    authDomain: 'styleleague-895e8.firebaseapp.com',
    storageBucket: 'styleleague-895e8.firebasestorage.app',
    measurementId: 'G-GK5B3ZNR7H',
  );
}
